name: 'nsei_pipeline'
version: '1.0.0'
config-version: 2

profile: 'nsei_pipeline'

model-paths: ["models"]
seed-paths:  ["seeds"]
test-paths:  ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  nsei_pipeline:
    +schema: seeds

models:
  nsei_pipeline:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

vars:
  run_date: "{{ run_started_at.strftime('%Y-%m-%d') }}"